name: sysfoo-ci-pipeline
on: push
jobs:
  sysfoo-ci-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Welcome to sysfoo"
        
      - name: code checkout
        uses: actions/checkout@v6
        
      - name: Test
        run: mvn test
        
      - name: clean
        run: mvn clean
        
      - name: package
        run: mvn package

      - name: View files
        run: ls -lrt
